version: '3'
services:
    chat:
        build:
            context: ./
        environment:
            - OPENAI_API_KEY=${OPENAI_API_KEY}
        ports:
            - 80:80
        volumes:
            - ./:/usr/local/app
            - ./nginx/default:/etc/nginx/sites-available/default
        container_name: chat
