version: '3'
services:
    chat:
        build:
            context: ./
        environment:
            - OPENAI_API_KEY=${OPENAI_API_KEY}
        volumes:
            - ./app:/usr/local/app
        container_name: chat
