version: '3'
services:
    chat:
        build:
            context: ./
            args:
                - ENV=${ENV}
        environment:
            - OPENAI_API_KEY=${OPENAI_API_KEY}
        ports:
            - ${NGINX_PORT}:80
        volumes:
            - ./:/usr/local/app
            - ./nginx/default:/etc/nginx/sites-available/default
            - /usr/local/app/frontend/node_modules
