name: Python application

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest
      - name: Lint with ruff
        run: |
          ruff --output-format=github --config=ruff.toml .
      - name: Test with pytest
        run: |
          pytest
