name: Python application

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
      - name: Cache pipenv dependencies
        id: cache-pipenv
        uses: actions/cache@v3
        with:
          path: |
            ~/.local/share/virtualenvs
            ./Pipfile.lock
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv-
      - name: Install dependencies with pipenv
        run: |
          pipenv install --dev
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
      - name: Lint with ruff
        run: |
          pipenv run ruff --output-format=github --config=ruff.toml .
      - name: Test with pytest
        run: |
          pipenv run pytest
